formatter: markdown table

settings:
  lockfile: false

sections:
  show:
    - requirements
    - providers
    - modules
    - resources
    - inputs
    - outputs

output:
  file: README.md
  mode: inject
